#These docs are autogenerated with your API key and version in your Deploy tab within the Roboflow application

from roboflow import Roboflow
import cv2
import os
#import matplotlib.pyplot as plt

#rf = Roboflow(api_key="bjZ0vSNzMZZZz6TBZHQY")
#project = rf.workspace().project("testes-og3ls")
#model = project.version(1).model


img = cv2.VideoCapture(1,cv2.CAP_DSHOW)
i = 4
print(img.get(cv2.CAP_PROP_FRAME_HEIGHT))
print(img.get(cv2.CAP_PROP_FRAME_WIDTH))
print(img.get(cv2.CAP_PROP_FPS))
img.set(cv2.CAP_PROP_AUTOFOCUS, 0) # turn the autofocus off
img.set(3, 1280)
img.set(4, 720)
img.set(cv2.CAP_PROP_FPS, 60)
print(img.get(cv2.CAP_PROP_FRAME_HEIGHT))
print(img.get(cv2.CAP_PROP_FRAME_WIDTH))
print(img.get(cv2.CAP_PROP_FPS))
while True:
    
    ret,frame = img.read()
    cv2.imshow('frame',frame)
    path = 'FotosCaixa'
    if cv2.waitKey(1) & 0xFF == ord('s'):
        cv2.imwrite(os.path.join(path , f'frame{i}.jpg'), frame)
        i = i+1
    elif cv2.waitKey(1) & 0xFF == ord('q'):
        break
    
   


img.release()
cv2.destroyAllWindows